name:        ptt
version:     0.1.0
author:      "Adrián Lattes"
description: "Plaintext time tracker with support for pomodoro technique"
git: "https://github.com/haztecaso/ptt"

extra-source-files:
- readme.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- data-timeout
- parsec
- text
- text-show
- time 
- either

library:
  source-dirs: src

executables:
  ptt:
    main:                Main.hs
    source-dirs:         app 
    ghc-options:
    - -haddock
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-tabs
    - -fwarn-orphans
    - -fwarn-incomplete-patterns
    - -fwarn-unused-imports
    - -Wincomplete-patterns
    dependencies:
    - ptt
    - parseargs

tests:
  ptt-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ptt
